var researchersAppModule = angular.module('researchersAppModule', ['ui.bootstrap']);
researchersAppModule.controller('adminPageController', adminPageController);
researchersAppModule.controller('adminPageModalController', adminPageModalController);
researchersAppModule.controller('adminManageCoursePageController', adminManageCoursePageController);
researchersAppModule.controller('adminAddExisitingUsersPageModalController', adminAddExisitingUsersPageModalController);
researchersAppModule.controller('adminRemoveExisitingUsersPageModalController', adminRemoveExisitingUsersPageModalController);
researchersAppModule.controller('adminChangeCourseNamePageModalController', adminChangeCourseNamePageModalController);
researchersAppModule.controller('adminAddNewUserPageModalController', adminAddNewUserPageModalController);
researchersAppModule.controller('adminAddNewFormPageModalController', adminAddNewFormPageModalController);
